Repository aeecleclair/Titan, pull requests merged in 2023-09, with the labels that each got.

#148 Disable notifications on Titan Web
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/quit_dialog.dart
  lib/main.dart
Labels: ready for review, fix bug, web

#131 Adding first opening notification pop up
  lib/drawer/providers/display_notification_popup.dart
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/notification_popup.dart
  lib/service/providers/topic_provider.dart
Labels: enhancement, core, ready for review

#161 Fixing router
  lib/home/router.dart
  lib/home/ui/days_event.dart
  lib/loan/ui/pages/admin_page/on_going_loan.dart
Labels: core, ready for review, fix bug

#156 Adding condition to properly discriminate delay of date to today
  lib/event/tools/functions.dart
Labels: core, ready for review, fix bug

#155 Fixing Centralisation
  lib/amap/ui/pages/presentation_page/text.dart
  lib/centralisation/tools/functions.dart
  lib/centralisation/ui/pages/main_page.dart
  lib/tools/ui/text_with_hyper_link.dart
Labels: enhancement, ready for review, centralisation

#162 Fixing notifications
  lib/cinema/repositories/cinema_topic_repository.dart
  lib/cinema/ui/pages/main_page/main_page.dart
  lib/service/local_notification_service.dart
Labels: notification, ready for review, fix bug

#167 Fix background notifications
  lib/service/tools/setup.dart
Labels: notification, ready for review, fix bug

#169 fix: Adding temporary solution to handle timezone
  lib/cinema/ui/pages/detail_page/detail_page.dart
  lib/cinema/ui/pages/main_page/session_card.dart
  lib/service/local_notification_service.dart
Labels: notification, ready for review, fix bug

#168 Fixing-login
  lib/login/ui/create_account_page.dart
  lib/login/ui/recover_password.dart
Labels: core, ready for review

#175 fix: updating formatDelayToToday
  lib/event/tools/functions.dart
  lib/home/ui/home.dart
Labels: ready for review, fix bug
