Repository aeecleclair/Titan, pull requests merged in 2023-08, with the labels that each got.

#97 Using either and svgPicture to specify module icon
  lib/amap/router.dart
  lib/booking/router.dart
  lib/cinema/router.dart
  lib/drawer/class/module.dart
  lib/drawer/ui/module.dart
  lib/event/router.dart
  lib/home/router.dart
  lib/loan/router.dart
  lib/settings/ui/pages/modules_page/modules_page.dart
  lib/tombola/router.dart
  lib/vote/router.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, core, ready to review

#95 Improving login
  lib/login/providers/animation_provider.dart
  lib/login/router.dart
  lib/login/tools/constants.dart
  lib/login/ui/auth.dart
  lib/login/ui/create_account_page.dart
  lib/login/ui/forget.dart
  lib/login/ui/login_field.dart
  lib/login/ui/main_page.dart
  lib/login/ui/recover_password.dart
  lib/login/ui/register.dart
  lib/login/ui/sign_in.dart
  lib/login/ui/sign_in_up_bar.dart
  lib/main.dart
  lib/settings/ui/pages/change_pass/password_strength.dart
  lib/tools/middlewares/authenticated_middleware.dart
  lib/tools/ui/app_template.dart
Labels: core, ready to review, fix bug

#99 Fix: Resetting the loading arrow when the loading popup is closed without logging in
  lib/auth/providers/openid_provider.dart
Labels: core, ready to review, fix bug

#100 Improving login page for web
  assets/images/eclair.png
  assets/images/login.svg
  assets/web/AMAP.webp
  assets/web/Calendrier.webp
  assets/web/Ciné.webp
  assets/web/Parametres.webp
  assets/web/Pret.webp
  assets/web/Tombola.webp
  assets/web/Vote.webp
  assets/web/back.webp
  lib/login/class/screen_shot.dart
  lib/login/router.dart
  lib/login/ui/app_sign_in.dart
  lib/login/ui/sign_in.dart
  lib/login/ui/web/left_panel.dart
  lib/login/ui/web/right_panel.dart
  lib/login/ui/web/web_sign_in.dart
  pubspec.lock
  pubspec.yaml
Labels: enhancement, core, ready to review

#98 Fix: redirecting from / to the first ordered module
  lib/admin/ui/admin.dart
  lib/admin/ui/top_bar.dart
  lib/amap/ui/amap.dart
  lib/amap/ui/top_bar.dart
  lib/booking/ui/booking.dart
  lib/booking/ui/top_bar.dart
  lib/cinema/ui/cinema.dart
  lib/cinema/ui/top_bar.dart
  lib/drawer/ui/bottom_bar.dart
  lib/drawer/ui/custom_drawer.dart
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/drawer_top_bar.dart
  lib/drawer/ui/list_module.dart
  lib/drawer/ui/module.dart
  lib/event/ui/event.dart
  lib/home/ui/home.dart
  lib/home/ui/top_bar.dart
  lib/loan/ui/loan.dart
  lib/loan/ui/top_bar.dart
  lib/settings/providers/module_list_provider.dart
  lib/settings/ui/settings.dart
  lib/settings/ui/top_bar.dart
  lib/tombola/ui/tombola.dart
  lib/tombola/ui/top_bar.dart
  lib/tools/middlewares/authenticated_middleware.dart
  lib/tools/ui/top_bar.dart
  lib/vote/ui/top_bar.dart
  lib/vote/ui/vote.dart
Labels: core, ready to review, fix bug

#102 Fix/ fixing new mail dialog
  lib/drawer/providers/already_displayed_popup.dart
  lib/drawer/providers/display_quit_popup.dart
  lib/drawer/ui/bottom_bar.dart
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/email_change_popup.dart
  lib/drawer/ui/quit_dialog.dart
  lib/others/ui/email_change_popup.dart
  lib/user/repositories/user_repository.dart
Labels: core, ready to review, fix bug

#105 Feat/ adding on return on topbar
  lib/admin/ui/admin.dart
  lib/cinema/ui/cinema.dart
  lib/tools/ui/top_bar.dart
Labels: enhancement, core, ready to review

#106 Add layout builder constraints for web app refresher
  lib/tools/ui/refresher.dart
Labels: core, ready to review, fix bug

#103 Fix: Image uploading : Handling web case
  lib/vote/ui/pages/pretendance_pages/add_edit_pretendance.dart
Labels: core, ready to review, fix bug

#101 Centralisation Module
  lib/centralisation/class/module.dart
  lib/centralisation/class/section.dart
  lib/centralisation/providers/centralisation_section_provider.dart
  lib/centralisation/providers/favorites_providers.dart
  lib/centralisation/repositories/section_repository.dart
  lib/centralisation/router.dart
  lib/centralisation/tools/constants.dart
  lib/centralisation/tools/functions.dart
  lib/centralisation/ui/centralisation.dart
  lib/centralisation/ui/pages/liked_card.dart
  lib/centralisation/ui/pages/main_page.dart
  lib/centralisation/ui/pages/module_card.dart
  lib/centralisation/ui/pages/section_list.dart
  lib/login/ui/web/left_panel.dart
  lib/main.dart
  lib/router.dart
  lib/settings/providers/module_list_provider.dart
  lib/tools/repository/repository.dart
  lib/tools/ui/top_bar.dart
  windows/runner/Runner.rc
Labels: enhancement, ready to review, centralisation

#109 fix redirect
  lib/login/ui/create_account_page.dart
Labels: core, ready to review

#108 Advert module
  lib/advert/class/advert.dart
  lib/advert/class/announcer.dart
  lib/advert/class/tag.dart
  lib/advert/providers/advert_list_provider.dart
  lib/advert/providers/advert_poster_provider.dart
  lib/advert/providers/advert_posters_provider.dart
  lib/advert/providers/advert_provider.dart
  lib/advert/providers/all_announcer_list_provider.dart
  lib/advert/providers/announcer_list_provider.dart
  lib/advert/providers/announcer_provider.dart
  lib/advert/providers/is_advert_admin_provider.dart
  lib/advert/repositories/advert_poster_repository.dart
  lib/advert/repositories/advert_repository.dart
  lib/advert/repositories/announcer_repository.dart
  lib/advert/repositories/tag_repository.dart
  lib/advert/tools/constants.dart
  lib/advert/tools/functions.dart
  lib/advert/ui/pages/admin_page/admin_advert_card.dart
  lib/advert/ui/pages/admin_page/admin_page.dart
  lib/advert/ui/pages/advert.dart
  lib/advert/ui/pages/detail_page/detail.dart
  lib/advert/ui/pages/form_page/add_edit_advert_page.dart
  lib/advert/ui/pages/form_page/add_rem_announcer_page.dart
  lib/advert/ui/pages/form_page/text_entry.dart
  lib/advert/ui/pages/main_page/main_page.dart
  lib/advert/ui/router.dart
  lib/advert/ui/tools/advert_card.dart
  lib/advert/ui/tools/announcer_bar.dart
  lib/advert/ui/tools/tag_chip.dart
  lib/others/ui/no_internet_page.dart
  lib/router.dart
  lib/settings/providers/module_list_provider.dart
Labels: enhancement, ready to review, advert

#104 Change the way to handle closing dialog
  lib/drawer/ui/quit_dialog.dart
  lib/tools/ui/dialog.dart
Labels: core, ready to review, fix bug

#107 Fix/-fixing-back-going-to-loading-page
  lib/amap/ui/amap.dart
  lib/booking/ui/booking.dart
  lib/cinema/ui/cinema.dart
  lib/drawer/class/top_bar_callback.dart
  lib/drawer/providers/top_bar_callback_provider.dart
  lib/drawer/ui/custom_drawer.dart
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/drawer_top_bar.dart
  lib/drawer/ui/module.dart
  lib/event/ui/event.dart
  lib/home/ui/home.dart
  lib/loan/ui/loan.dart
  lib/login/ui/main_page.dart
  lib/main.dart
  lib/others/ui/loading_page.dart
  lib/others/ui/no_internet_page.dart
  lib/others/ui/update_page.dart
  lib/router.dart
  lib/settings/ui/settings.dart
  lib/tombola/ui/tombola.dart
  lib/tools/middlewares/authenticated_middleware.dart
  lib/tools/ui/top_bar.dart
  lib/vote/ui/vote.dart
Labels: core, ready to review, fix bug

#48 Adding button to delete list
  lib/vote/repositories/pretendance_repository.dart
  lib/vote/tools/constants.dart
  lib/vote/ui/pages/admin_page/admin_page.dart
  pubspec.lock
Labels: ready for review, fix bug

#111 Fixing onNo button behavior
  lib/tools/ui/dialog.dart
Labels: core, ready for review, fix bug

#110 Fix regex dots + allow centraliens-lyon.net
  lib/login/tools/constants.dart
Labels: enhancement, ready for review, fix bug

#117 Reorder-Centralisation-favorite-modules
  lib/centralisation/providers/favorites_providers.dart
  lib/centralisation/ui/pages/main_page.dart
Labels: enhancement, ready for review, centralisation

#61 Adding notification
  .env.template
  .gitignore
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  ios/Runner/AppDelegate.swift
  lib/cinema/notification_service.dart
  lib/cinema/providers/cinema_topic_provider.dart
  lib/cinema/repositories/cinema_topic_repository.dart
  lib/cinema/router.dart
  lib/cinema/ui/cinema.dart
  lib/cinema/ui/pages/main_page/session_card.dart
  lib/drawer/ui/bottom_bar.dart
  lib/drawer/ui/drawer_template.dart
  lib/drawer/ui/quit_dialog.dart
  lib/main.dart
  lib/service/class/message.dart
  lib/service/class/topic.dart
  lib/service/local_notification_service.dart
  lib/service/provider_list.dart
  lib/service/providers/firebase_token_expiration_provider.dart
  lib/service/providers/firebase_token_provider.dart
  lib/service/providers/messages_provider.dart
  lib/service/providers/topic_provider.dart
  lib/service/repositories/notification_repository.dart
  lib/service/tools/functions.dart
  lib/service/tools/setup.dart
  lib/settings/router.dart
  lib/settings/ui/pages/main_page/main_page.dart
  lib/settings/ui/pages/notification_page/notification_page.dart
  lib/tools/functions.dart
  lib/tools/middlewares/authenticated_middleware.dart
  lib/tools/middlewares/notification_middleware.dart
  pubspec.lock
  pubspec.yaml
  web/firebase-messaging-sw.js
Labels: enhancement, notification, ready for review

#126 Removing blue as loader color
  lib/admin/ui/pages/add_loaner_page/add_loaner_page.dart
  lib/advert/ui/pages/form_page/add_rem_announcer_page.dart
  lib/event/ui/pages/main_page/main_page.dart
Labels: core, ready for review, fix bug

#125 Exiting app when going back on drawer
  lib/main.dart
Labels: core, ready for review, bug, android

#128 Adding formerstudent AccountType
  lib/login/class/account_type.dart
  lib/login/tools/functions.dart
Labels: ready for review

#118 add edit module visibility page
  lib/admin/class/module_visibility.dart
  lib/admin/providers/all_groups_list_provider.dart
  lib/admin/providers/all_my_module_roots_list_provider.dart
  lib/admin/providers/module_root_list_provider.dart
  lib/admin/providers/module_visibility_list_provider.dart
  lib/admin/repositories/module_visibility_repository.dart
  lib/admin/router.dart
  lib/admin/tools/constants.dart
  lib/admin/ui/pages/edit_module_visibility/edit_module_visibility.dart
  lib/admin/ui/pages/main_page/main_page.dart
  lib/main.dart
  lib/others/tools/constants.dart
  lib/others/ui/no_module.dart
  lib/router.dart
  lib/settings/providers/module_list_provider.dart
  lib/tools/class/path_forwarding.dart
  lib/tools/middlewares/authenticated_middleware.dart
  lib/tools/providers/path_forwarding_provider.dart
Labels: enhancement, core, ready for review, waiting backend

#129 Fix/-Fixing-visibility
  lib/admin/class/module_visibility.dart
  lib/admin/ui/pages/edit_module_visibility/edit_module_visibility.dart
  lib/admin/ui/pages/edit_module_visibility/modules_expansion_panel.dart
Labels: core, ready for review, fix bug

#132 fix page type to prevent a mix of QCupertinoPage and QMaterialPage
  lib/login/router.dart
  lib/main.dart
Labels: core, ready for review, fix bug

#130 Color change of booking card depending on decision
  lib/booking/ui/booking_card.dart
Labels: enhancement, ready for review, booking

#124 Notification-improvment
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/admin/notification_service.dart
  lib/admin/providers/group_list_provider.dart
  lib/advert/notification_service.dart
  lib/amap/notification_service.dart
  lib/amap/ui/amap.dart
  lib/booking/notification_service.dart
  lib/booking/ui/booking.dart
  lib/cinema/notification_service.dart
  lib/cinema/ui/pages/detail_page/detail_page.dart
  lib/cinema/ui/pages/main_page/session_card.dart
  lib/drawer/ui/drawer_template.dart
  lib/event/notification_service.dart
  lib/event/ui/event.dart
  lib/event/ui/pages/main_page/main_page.dart
  lib/loan/notification_service.dart
  lib/loan/ui/loan.dart
  lib/service/local_notification_service.dart
  lib/service/provider_list.dart
  lib/service/tools/setup.dart
  lib/tombola/notification_service.dart
  lib/tombola/ui/tombola.dart
  lib/tools/middlewares/notification_middleware.dart
  lib/vote/notification_service.dart
Labels: core, notification, ready for review, waiting backend

#136 Loading user module instead of the whole list
  lib/others/ui/no_module.dart
Labels: core, ready for review, fix bug

#145 Fix/ fixing advert
  lib/advert/notification_service.dart
  lib/advert/repositories/announcer_repository.dart
  lib/advert/ui/pages/detail_page/detail.dart
  lib/advert/ui/pages/main_page/main_page.dart
  lib/advert/ui/tools/advert_card.dart
  lib/tools/constants.dart
  lib/tools/ui/text_with_hyper_link.dart
Labels: ready for review, fix bug, advert

#135 Fix booking card size + booking cards position
  lib/booking/ui/booking_card.dart
  lib/booking/ui/pages/main_page/main_page.dart
Labels: enhancement, ready for review, booking

#146 Fix redirectUri for web
  lib/auth/providers/openid_provider.dart
Labels: ready for review, fix bug, waiting backend

#142 Fix/ allow admin to interact with booking until its end is past
  lib/booking/ui/booking_card.dart
Labels: ready for review, fix bug, booking
