Repository aeecleclair/Titan, pull requests merged in 2023-11, with the labels that each got.

#202 Actions web fix
  .github/workflows/release-web.yml
  Dockerfile
Labels: fix bug, ci/cd, github_actions

#96 Lint and format config and workflow
  .github/workflows/lintandformat.yml
  .vscode/launch.json
  .vscode/settings.json
  README.md
  lib/event/ui/pages/admin_page/list_event.dart
  lib/raffle/class/pack_ticket.dart
  lib/raffle/providers/tombola_logos_provider.dart
  lib/raffle/providers/user_tickets_provider.dart
  lib/raffle/repositories/raffle_detail_repository.dart
  lib/raffle/repositories/tombola_logo_repository.dart
  lib/raffle/router.dart
  lib/raffle/ui/components/blue_btn.dart
  lib/raffle/ui/pages/admin_module_page/admin_module_page.dart
  lib/raffle/ui/pages/admin_module_page/tombola_card.dart
  lib/raffle/ui/pages/creation_edit_page/ticket_handler.dart
  lib/raffle/ui/pages/creation_edit_page/user_cash_ui.dart
  lib/raffle/ui/pages/creation_edit_page/winning_ticket_card.dart
  lib/raffle/ui/pages/creation_edit_page/winning_ticket_handler.dart
  lib/raffle/ui/pages/main_page/ticket_card.dart
  lib/raffle/ui/pages/raffle_page/buy_type_ticket_card.dart
  lib/service/tools/setup.dart
  lib/settings/ui/pages/notification_page/notification_page.dart
  lib/tools/ui/layouts/horizontal_list_view.dart
  lib/tools/ui/widgets/dialog.dart
  lib/vote/class/voter.dart
  lib/vote/providers/can_vote_provider.dart
  lib/vote/providers/voter_list_provider.dart
  lib/vote/providers/voting_group_list_provider.dart
Labels: ci/cd

#211 Spliting for web
  lib/admin/router.dart
  lib/advert/router.dart
  lib/amap/router.dart
  lib/booking/router.dart
  lib/centralisation/router.dart
  lib/cinema/router.dart
  lib/event/router.dart
  lib/home/router.dart
  lib/loan/router.dart
  lib/login/router.dart
  lib/others/ui/no_internet_page.dart
  lib/others/ui/no_module.dart
  lib/others/ui/update_page.dart
  lib/raffle/router.dart
  lib/router.dart
  lib/settings/router.dart
  lib/tools/middlewares/deferred_middleware.dart
  lib/vote/router.dart
  pubspec.lock
Labels: ready for review, web

#220 fix: forcing promo to be an int
  lib/login/ui/pages/create_account_page/create_account_page.dart
Labels: core, ready for review, fix bug
