Repository aeecleclair/Titan, pull requests merged in 2024-02, with the labels that each got.

#251 fix/events issues
  lib/event/ui/pages/admin_page/list_event.dart
  lib/tools/functions.dart
  test/booking/booking_test.dart
  test/event/event_test.dart
Labels: enhancement, ready for review, event

#250 feat: adding persistent scrollbar
  lib/drawer/ui/list_module.dart
Labels: enhancement, core, ready for review

#246 fix: removing wrong image bytes retrieval
  lib/cinema/ui/pages/session_pages/add_edit_session.dart
Labels: ready for review, fix bug

#256 fix : event recurrences and scrolling issues
  lib/event/ui/pages/event_pages/add_edit_event_page.dart
  lib/event/ui/pages/main_page/main_page.dart
Labels: ready for review, fix bug, event

#241 Fix/fixing-nicknamedless-user-contender-card
  lib/amap/ui/pages/admin_page/adding_user_card.dart
  lib/amap/ui/pages/admin_page/user_cash_ui.dart
  lib/drawer/ui/drawer_top_bar.dart
  lib/raffle/ui/pages/admin_module_page/adding_user_card.dart
  lib/raffle/ui/pages/creation_edit_page/user_cash_ui.dart
  lib/settings/ui/pages/main_page/main_page.dart
  lib/vote/class/members.dart
  lib/vote/ui/components/member_card.dart
  pubspec.lock
Labels: ready for review, fix bug, vote

#288 Fix(AMAP) : Searchbar
  lib/amap/providers/cash_list_provider.dart
  lib/amap/providers/focus_provider.dart
  lib/amap/ui/pages/admin_page/account_handler.dart
  lib/loan/ui/pages/admin_page/loan_history.dart
  lib/loan/ui/pages/admin_page/on_going_loan.dart
  lib/tools/ui/widgets/styled_search_bar.dart
  test/amap/cash_list_provider_test.dart
  test/amap/focus_provider_test.dart
Labels: ready for review, fix bug

#290 Fix/enabling validator with empty value
  lib/amap/tools/constants.dart
  lib/amap/ui/pages/product_pages/add_edit_product.dart
  lib/tools/ui/widgets/text_entry.dart
Labels: ready for review, fix bug

#292 feat: adding no data state
  lib/admin/providers/section_logo_provider.dart
  lib/admin/providers/simple_groups_groups_provider.dart
  lib/advert/providers/advert_posters_provider.dart
  lib/amap/providers/delivery_order_list_provider.dart
  lib/cinema/providers/session_poster_map_provider.dart
  lib/loan/providers/admin_history_loan_list_provider.dart
  lib/loan/providers/admin_loan_list_provider.dart
  lib/loan/providers/loaners_items_provider.dart
  lib/raffle/providers/raffle_stats_map_provider.dart
  lib/raffle/providers/tombola_logos_provider.dart
  lib/tools/providers/map_provider.dart
  lib/tools/ui/builders/auto_loader_child.dart
  lib/vote/providers/contender_logos_provider.dart
  lib/vote/providers/sections_contender_provider.dart
  lib/vote/providers/sections_stats_provider.dart
  test/tools/providers/map_notifier_test.dart
Labels: core, ready for review, fix bug

#237 Add Plausible to MyECL
  .env.template
  .github/workflows/release-mobile.yml
  .github/workflows/release-web.yml
  lib/admin/router.dart
  lib/advert/router.dart
  lib/amap/router.dart
  lib/booking/router.dart
  lib/centralisation/router.dart
  lib/cinema/router.dart
  lib/event/router.dart
  lib/home/router.dart
  lib/loan/router.dart
  lib/main.dart
  lib/raffle/router.dart
  lib/router.dart
  lib/settings/router.dart
  lib/tools/functions.dart
  lib/tools/plausible/plausible.dart
  lib/tools/plausible/plausible_observer.dart
  lib/vote/router.dart
  pubspec.lock
  pubspec.yaml
Labels: ready for review

#296 Fix(Advert): Overflow in web advert page
  lib/advert/ui/components/advert_card.dart
Labels: ready for review

#299 Fix(Amap) Use constants for slots
  lib/amap/class/order.dart
  lib/amap/tools/constants.dart
  lib/amap/tools/functions.dart
  lib/amap/ui/components/order_ui.dart
  lib/amap/ui/pages/main_page/collection_slot_selector.dart
  test/amap/amap_test.dart
Labels: ready for review
