Repository aeecleclair/Titan, pull requests merged in 2024-06, with the labels that each got.

#376 Fix loan
  lib/loan/ui/pages/loan_group_page/add_edit_button.dart
  lib/loan/ui/pages/loan_group_page/add_edit_loan_page.dart
  lib/loan/ui/pages/loan_group_page/item_bar.dart
  lib/loan/ui/pages/loan_group_page/start_date_entry.dart
Labels: fix bug, loan

#373 password format verification
  lib/login/tools/constants.dart
  lib/login/ui/components/login_field.dart
Labels: core

#382 Fix PH filesaver for web
  lib/ph/ui/pages/past_ph_selection_page/ph_list.dart
Labels: fix bug, ph

#383 Publish 0.9.0+124 Alpha
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner.xcodeproj/xcshareddata/xcschemes/Alpha.xcscheme
  pubspec.yaml
Labels: build, release

#390 fix: password regex [!@#$%^&*(),.?":{}|<>\-_[\]+=;]
  lib/login/ui/components/login_field.dart
Labels: fix bug

#391 bump version to 126
  pubspec.yaml
Labels: build, release
