Repository aeecleclair/Titan, pull requests merged in 2024-04, with the labels that each got.

#348 Prepare for new release
  pubspec.yaml
Labels: ready for review, build

#353 Init logs and escape messages and refactor loggers
  lib/service/tools/setup.dart
  lib/tools/logs/file_logger_output.dart
  lib/tools/logs/log.dart
  lib/tools/logs/logger.dart
  lib/tools/logs/logger_output.dart
  lib/tools/logs/print_logger_output.dart
  lib/tools/repository/logo_repository.dart
  lib/tools/repository/repository.dart
Labels: enhancement, core, fix bug

#347 Improve gradle build file
  android/app/build.gradle
  android/app/src/main/kotlin/com/example/myecl/MainActivity.kt
Labels: ready for review, android, build
