Repository aeecleclair/Titan, pull requests merged in 2024-03, with the labels that each got.

#304 Fix overflow on admin calendar pop up
  lib/booking/ui/calendar/calendar_dialog.dart
  lib/booking/ui/calendar/calendar_dialog_button.dart
Labels: ready for review

#242 Recommendation
  lib/recommendation/class/recommendation.dart
  lib/recommendation/providers/is_recommendation_admin_provider.dart
  lib/recommendation/providers/recommendation_list_provider.dart
  lib/recommendation/providers/recommendation_logo_map_provider.dart
  lib/recommendation/providers/recommendation_logo_provider.dart
  lib/recommendation/providers/recommendation_provider.dart
  lib/recommendation/repositories/recommendation_logo_repository.dart
  lib/recommendation/repositories/recommendation_repository.dart
  lib/recommendation/router.dart
  lib/recommendation/tools/constants.dart
  lib/recommendation/ui/pages/add_edit_page.dart
  lib/recommendation/ui/pages/information_page.dart
  lib/recommendation/ui/pages/main_page.dart
  lib/recommendation/ui/widgets/recommendation_card.dart
  lib/recommendation/ui/widgets/recommendation_card_layout.dart
  lib/recommendation/ui/widgets/recommendation_template.dart
  lib/router.dart
  lib/settings/providers/module_list_provider.dart
  lib/tools/functions.dart
  lib/tools/ui/widgets/text_entry.dart
  test/recommendation/recommendation_list_provider_test.dart
Labels: enhancement, ready for review, waiting backend

#319 Fix: use PopScope instead of deprecated WillPopScope
  android/app/src/main/AndroidManifest.xml
  lib/main.dart
Labels: core, ready for review

#322 Fix recommendation module after MapNotifier rework
  lib/recommendation/providers/recommendation_logo_map_provider.dart
  lib/recommendation/ui/pages/add_edit_page.dart
  lib/recommendation/ui/widgets/recommendation_card.dart
Labels: ready for review, fix bug

#195 feat: use flavor for host, scheme and logo
  .env.template
  .github/workflows/build.yml
  .github/workflows/release-mobile.yml
  .github/workflows/release-web.yml
  .github/workflows/test.yml
  .vscode/launch.json
  README.md
  android/app/build.gradle
  assets/images/icon_prod.png
  assets/images/logo_prod.png
  flutter_launcher_icons-Prod.yaml
  ios/Flutter/AppFrameworkInfo.plist
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  lib/admin/providers/group_logo_provider.dart
  lib/advert/repositories/advert_poster_repository.dart
  lib/auth/providers/openid_provider.dart
  lib/cinema/repositories/session_poster_repository.dart
  lib/drawer/ui/drawer_top_bar.dart
  lib/login/ui/app_sign_in.dart
  lib/login/ui/pages/sign_in_page/sign_in_page.dart
  lib/login/ui/web/left_panel.dart
  lib/raffle/repositories/tombola_logo_repository.dart
  lib/service/local_notification_service.dart
  lib/settings/ui/pages/main_page/main_page.dart
  lib/tools/functions.dart
  lib/tools/repository/repository.dart
  lib/vote/repositories/contender_logo_repository.dart
  pubspec.yaml
Labels: core, ready for review

#121 DO NOT MERGE !!! Using-utc-datetime-to-comunicate-with-api
  lib/advert/class/advert.dart
  lib/amap/class/delivery.dart
  lib/amap/class/order.dart
  lib/booking/class/booking.dart
  lib/cinema/class/session.dart
  lib/event/class/event.dart
  lib/loan/class/loan.dart
  lib/login/class/create_account.dart
  lib/recommendation/class/recommendation.dart
  lib/service/class/message.dart
  lib/settings/ui/pages/edit_user_page/edit_user_page.dart
  lib/tools/functions.dart
  lib/user/class/user.dart
  test/admin/group_list_provider_test.dart
  test/amap/amap_test.dart
  test/booking/booking_test.dart
  test/cinema/cinema_test.dart
  test/tools/tools_test.dart
  test/user/user_test.dart
Labels: enhancement, core, ready for review, waiting backend

#326 Build PR when a build label is added
  .github/workflows/build.yml
Labels: build

#310 Change loan history order
  lib/loan/class/loan.dart
  lib/loan/tools/constants.dart
  lib/loan/ui/pages/admin_page/loan_card.dart
  lib/loan/ui/pages/admin_page/loan_history.dart
  test/loan/loan_test.dart
Labels: ready for review, loan

#327 Add trailing comma
  lib/admin/ui/pages/add_loaner_page/add_loaner_page.dart
  lib/admin/ui/pages/edit_page/search_user.dart
  lib/advert/ui/components/advert_card.dart
  lib/loan/providers/item_list_provider.dart
  lib/phonebook/providers/association_member_list_provider.dart
  lib/phonebook/ui/pages/association_editor_page/association_editor_page.dart
  lib/tools/providers/list_notifier.dart
  lib/tools/providers/single_notifier.dart
  test/loan/loan_test.dart
Labels: ready for review, build

#331 Support flavor on the web using flutter `dart-define`
  .github/workflows/build.yml
  .github/workflows/release-web.yml
  README.md
  lib/tools/functions.dart
Labels: core, fix bug, ci/cd

#329 Fix plausible
  lib/phonebook/router.dart
  lib/recommendation/router.dart
Labels: ready for review, fix bug, build

#330 Fix notification
  lib/service/local_notification_service.dart
Labels: notification, ready for review, fix bug, build

#328 Fix Loan Item List
  lib/loan/class/item.dart
  lib/loan/providers/end_provider.dart
  lib/loan/ui/pages/item_group_page/add_edit_item_page.dart
  test/loan/loan_test.dart
Labels: ready for review, fix bug, loan, build

#341 Fix refresher issue
  lib/phonebook/providers/association_member_list_provider.dart
  lib/phonebook/providers/association_provider.dart
  lib/phonebook/repositories/association_repository.dart
  lib/phonebook/ui/pages/admin_page/admin_page.dart
  lib/phonebook/ui/pages/association_creation_page/association_creation_page.dart
  lib/phonebook/ui/pages/association_editor_page/association_editor_page.dart
  lib/phonebook/ui/pages/association_page/association_page.dart
  lib/phonebook/ui/pages/main_page/main_page.dart
  lib/phonebook/ui/pages/member_detail_page/member_detail_page.dart
Labels: ready for review, fix bug, phonebook, build

#337 Fix a mistake in readme
  README.md
Labels: documentation, ready for review
