Repository aeecleclair/Titan, pull requests merged in 2024-09, with the labels that each got.

#351 Fix phonebook and CoreGroup associated with Association
  lib/phonebook/class/association.dart
  lib/phonebook/class/membership.dart
  lib/phonebook/providers/association_list_provider.dart
  lib/phonebook/providers/association_member_list_provider.dart
  lib/phonebook/providers/association_member_sorted_list_provider.dart
  lib/phonebook/providers/member_role_tags_provider.dart
  lib/phonebook/providers/phonebook_admin_provider.dart
  lib/phonebook/repositories/association_repository.dart
  lib/phonebook/router.dart
  lib/phonebook/tools/constants.dart
  lib/phonebook/tools/function.dart
  lib/phonebook/ui/pages/admin_page/admin_page.dart
  lib/phonebook/ui/pages/admin_page/delete_button.dart
  lib/phonebook/ui/pages/admin_page/editable_association_card.dart
  lib/phonebook/ui/pages/admin_page/edition_button.dart
  lib/phonebook/ui/pages/association_editor_page/association_editor_page.dart
  lib/phonebook/ui/pages/association_editor_page/association_information_editor.dart
  lib/phonebook/ui/pages/association_editor_page/member_editable_card.dart
  lib/phonebook/ui/pages/association_page/member_card.dart
  lib/phonebook/ui/pages/association_page/web_member_card.dart
  lib/phonebook/ui/pages/main_page/main_page.dart
  lib/phonebook/ui/pages/membership_editor_page/membership_editor_page.dart
  lib/tools/constants.dart
Labels: ready for review

#420 Release 0.10.0+130
  pubspec.yaml
Labels: build, release

#429 Update on past ph page
  lib/ph/tools/constants.dart
  lib/ph/ui/pages/admin_page/admin_ph_card.dart
  lib/ph/ui/pages/past_ph_selection_page/ph_card.dart
  lib/ph/ui/pages/past_ph_selection_page/ph_list.dart
  lib/tools/ui/layouts/card_button.dart
  lib/tools/ui/layouts/card_layout.dart
Labels: ready for review, ph

#432 Phonebook member cards : left-aligning on mobile, adding profile pictures on web
  lib/phonebook/ui/pages/association_page/member_card.dart
  lib/phonebook/ui/pages/association_page/web_member_card.dart
Labels: ready for review, fix bug, phonebook

#435 fix: handling loading case as no data case
  lib/tools/providers/should_notify_provider.dart
Labels: fix bug

#426 fix: adding missing tokenExpireWrapper
  lib/purchases/ui/pages/main_page/main_page.dart
  lib/purchases/ui/pages/scan_page/scan_dialog.dart
  lib/purchases/ui/pages/scan_page/scan_page.dart
  lib/purchases/ui/pages/scan_page/ticket_card.dart
  lib/purchases/ui/pages/user_list_page/user_list_page.dart
Labels: fix bug
