Repository aeecleclair/Titan, pull requests merged in 2025-01, with the labels that each got.

#448 Notification working
  lib/cinema/ui/pages/detail_page/detail_page.dart
  lib/ph/notification_service.dart
  lib/service/class/message.dart
  lib/service/local_notification_service.dart
  lib/service/tools/setup.dart
  pubspec.yaml
Labels: notification, fix bug

#462 Bump version 1.0.0
  pubspec.yaml
Labels: waiting backend, release

#447 Add Schools system
  lib/admin/class/school.dart
  lib/admin/providers/school_id_provider.dart
  lib/admin/providers/school_list_provider.dart
  lib/admin/providers/school_provider.dart
  lib/admin/repositories/school_repository.dart
  lib/admin/router.dart
  lib/admin/tools/constants.dart
  lib/admin/tools/function.dart
  lib/admin/ui/components/item_card_ui.dart
  lib/admin/ui/pages/add_group_page/add_group_page.dart
  lib/admin/ui/pages/add_loaner_page/add_loaner_page.dart
  lib/admin/ui/pages/add_school_page/add_school_page.dart
  lib/admin/ui/pages/edit_group_page/edit_group_page.dart
  lib/admin/ui/pages/edit_group_page/results.dart
  lib/admin/ui/pages/edit_group_page/search_user.dart
  lib/admin/ui/pages/edit_module_visibility/modules_expansion_panel.dart
  lib/admin/ui/pages/edit_school_page/edit_school_page.dart
  lib/admin/ui/pages/group_page/group_button.dart
  lib/admin/ui/pages/group_page/group_page.dart
  lib/admin/ui/pages/group_page/group_ui.dart
  lib/admin/ui/pages/main_page/main_page.dart
  lib/admin/ui/pages/main_page/menu_card_ui.dart
  lib/admin/ui/pages/school_page/school_button.dart
  lib/admin/ui/pages/school_page/school_page.dart
  lib/admin/ui/pages/school_page/school_ui.dart
  lib/phonebook/ui/pages/association_creation_page/association_creation_page.dart
Labels: enhancement, core, waiting backend
