Repository aeecleclair/Titan, pull requests merged in 2025-05, with the labels that each got.

#509 Support per flavor url scheme
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  ios/Podfile.lock
  ios/Runner.xcodeproj/project.pbxproj
  ios/Runner/Info.plist
Labels: enhancement, payment

#512 Rename workflows
  .github/workflows/lintandformat.yml
  .github/workflows/release-mobile.yml
  .github/workflows/release-web.yml
Labels: workflow

#511 Fix myeclpay
  lib/paiement/class/history.dart
  lib/paiement/tools/functions.dart
  lib/paiement/ui/components/transaction_card.dart
  lib/paiement/ui/pages/devices_page/add_device_button.dart
  lib/paiement/ui/pages/devices_page/device_item.dart
  lib/paiement/ui/pages/devices_page/devices_page.dart
  lib/paiement/ui/pages/fund_page/confirm_button.dart
  lib/paiement/ui/pages/main_page/account_card/account_card.dart
  lib/paiement/ui/pages/main_page/account_card/device_dialog_box.dart
  lib/paiement/ui/pages/stats_page/sum_up_chart.dart
  lib/paiement/ui/pages/store_admin_page/search_result.dart
  lib/paiement/ui/pages/store_admin_page/seller_right_card.dart
  lib/paiement/ui/pages/store_admin_page/store_admin_page.dart
  lib/paiement/ui/pages/store_stats_page/store_stats_page.dart
  lib/paiement/ui/pages/store_stats_page/store_transactions_detail.dart
  lib/paiement/ui/pages/store_stats_page/summary_card.dart
Labels: fix bug, myeclpay

#510 Release 1.2.1+148
  pubspec.yaml
Labels: release

#513 Fix: web and Home module
  android/.gitignore
  lib/main.dart
  lib/paiement/ui/pages/store_admin_page/seller_right_card.dart
  lib/settings/providers/module_list_provider.dart
Labels: ready for review, fix bug, web

#515 fix: using dialog for payment with revoked device
  lib/paiement/ui/components/transaction_card.dart
  lib/paiement/ui/pages/fund_page/fund_page.dart
  lib/paiement/ui/pages/main_page/account_card/account_card.dart
  lib/paiement/ui/pages/main_page/seller_card/store_seller_card.dart
  lib/paiement/ui/pages/pay_page/pay_page.dart
  pubspec.lock
Labels: myeclpay

#507 Ciné.webp > Cine.webp
  assets/web/Cine.webp
  lib/login/ui/web/right_panel.dart
  pubspec.yaml
Labels: ready for review, fix bug, web, build

#516 Release v1.2.2+149
  pubspec.yaml
Labels: build, release

#518 Add nginx config
  Dockerfile
  nginx.conf
Labels: web

#519 Release 1.2.3+150
  ios/Podfile.lock
  pubspec.yaml
Labels: release

#517 Don't build ipa on release
  .github/workflows/release-mobile.yml
Labels: workflow

#525 fix(MyECLPay): fundAmount error message
  lib/paiement/ui/pages/fund_page/confirm_button.dart
Labels: myeclpay

#524 feat(MyECLPay): sort device - order Actual -> Actif -> Revoked
  lib/paiement/tools/functions.dart
  lib/paiement/ui/pages/devices_page/devices_page.dart
Labels: myeclpay

#520 fix(MyECLPay): fix device card layout for large device name
  lib/paiement/ui/pages/devices_page/device_item.dart
  pubspec.lock
Labels: fix bug, myeclpay

#531 Fix: date locale
  lib/paiement/ui/components/transaction_card.dart
Labels: fix bug, myeclpay

#526 fix(MyECLPay): partially refunded, minus for refund in history and disallow refunding refunds
  lib/paiement/class/history.dart
  lib/paiement/ui/pages/store_stats_page/store_transactions_detail.dart
Labels: fix bug, myeclpay
