Repository aeecleclair/Titan, pull requests merged in 2025-06, with the labels that each got.

#530 Redirect URLs: depend on web/mobile and flavor
  .vscode/launch.json
  lib/auth/providers/openid_provider.dart
  lib/main.dart
  lib/paiement/tools/functions.dart
  lib/paiement/ui/pages/devices_page/devices_page.dart
  lib/paiement/ui/pages/fund_page/confirm_button.dart
  lib/paiement/ui/pages/main_page/account_card/account_card.dart
  lib/tools/functions.dart
Labels: core, ready for review, fix bug, myeclpay

#541 Hyperion 1.2.4+151
  pubspec.yaml
Labels: release

#542 Use `base64 -d >` on linux workers workflows
  .github/workflows/release-mobile.yml
Labels: workflow

#543 Release 1.2.5+152
  pubspec.yaml
Labels: release

#544 (_, _)
  lib/paiement/ui/pages/scan_page/scanner.dart
  test/event/confirmed_event_list_provider_test.dart
  test/event/event_list_provider_test.dart
  test/event/user_event_list_provider_test.dart
  test/user/profil_picture_provider_test.dart
  test/user/user_list_provider_test.dart
  test/vote/result_proovider_test.dart
  test/vote/sections_provider_test.dart
  test/vote/status_provider_test.dart
Labels: ready for review

#545 Allow read access even when last ToS are refused
  lib/paiement/providers/has_accepted_tos_provider.dart
  lib/paiement/ui/pages/devices_page/devices_page.dart
  lib/paiement/ui/pages/main_page/account_card/account_card.dart
  lib/paiement/ui/pages/main_page/main_page.dart
  lib/paiement/ui/pages/store_admin_page/search_result.dart
Labels: fix bug, waiting backend, myeclpay

#553 Fix: Centralisation JSON dynamic parsing
  lib/centralisation/class/section.dart
  lib/centralisation/repositories/section_repository.dart
Labels: ready for review, fix bug, centralisation

#555 Release 1.2.7+154
  pubspec.yaml
Labels: release
